FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src

# It's important to keep lines from here down to "COPY . ." identical in all Dockerfiles
# to take advantage of Docker's build cache, to speed up local container builds
COPY "Services/Identity/Identity.API/O2.Identity.API.csproj" "Services/Identity/Identity.API/"
COPY . .
WORKDIR "/src/Services/Identity/Identity.API/"
RUN dotnet restore "O2.Identity.API.csproj"

COPY . .
WORKDIR /src/Services/Identity/Identity.API
RUN dotnet publish --no-restore -c Release -o /app

FROM build AS publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "O2.Identity.API.dll"]
