//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.O2Bionics.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.O2Bionics.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument {0} ({1}) cannot exceed {2}..
        /// </summary>
        public static string ArgumentCannotExceed3 {
            get {
                return ResourceManager.GetString("ArgumentCannotExceed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument {0} ({1}) must be non-negative..
        /// </summary>
        public static string ArgumentMustBeNonNegative2 {
            get {
                return ResourceManager.GetString("ArgumentMustBeNonNegative2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument {0} ({1}) must be positive..
        /// </summary>
        public static string ArgumentMustBePositive2 {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must start with a..z or A..Z and consist of a..z, A..Z, digits 0..9..
        /// </summary>
        public static string LowerOrUpperCaseError {
            get {
                return ResourceManager.GetString("LowerOrUpperCaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be not empty string..
        /// </summary>
        public static string MustBeNotEmptyString {
            get {
                return ResourceManager.GetString("MustBeNotEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be not empty string..
        /// </summary>
        public static string MustBeNotEmptyStringError1 {
            get {
                return ResourceManager.GetString("MustBeNotEmptyStringError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be a valid uri..
        /// </summary>
        public static string MustBeValidUri {
            get {
                return ResourceManager.GetString("MustBeValidUri", resourceCulture);
            }
        }
    }
}
