//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.O2Bionics.ChatService.Widget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.O2Bionics.ChatService.Widget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine the Domain..
        /// </summary>
        public static string CannotDetermineDomainError {
            get {
                return ResourceManager.GetString("CannotDetermineDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat widget internal error..
        /// </summary>
        public static string ChatWidgetInternalError {
            get {
                return ResourceManager.GetString("ChatWidgetInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ({0}) must be active..
        /// </summary>
        public static string CustomerMustBeActiveError1 {
            get {
                return ResourceManager.GetString("CustomerMustBeActiveError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Domain is too long ({0})..
        /// </summary>
        public static string DomainIsTooLongError1 {
            get {
                return ResourceManager.GetString("DomainIsTooLongError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referer domain &apos;{0}&apos; must be workspace domain &apos;{1}&apos;..
        /// </summary>
        public static string RefererDomainMustBeWorkspaceDomainError2 {
            get {
                return ResourceManager.GetString("RefererDomainMustBeWorkspaceDomainError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many Chat Widget loads..
        /// </summary>
        public static string TooManyChatWidgetLoads {
            get {
                return ResourceManager.GetString("TooManyChatWidgetLoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many unknown domains..
        /// </summary>
        public static string TooManyUnknownDomainsError {
            get {
                return ResourceManager.GetString("TooManyUnknownDomainsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t show the Chat Widget on a page loaded from the unregistered domain &apos;{0}&apos;..
        /// </summary>
        public static string WidgetLoadedFromUnregisteredDomainError1 {
            get {
                return ResourceManager.GetString("WidgetLoadedFromUnregisteredDomainError1", resourceCulture);
            }
        }
    }
}
