//----------------------------------------------------------------------------------------------------
//    <auto-generated>
//    This code was generated by SettingsGenerator template.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//    </auto-generated>
//----------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Com.O2Bionics.ChatService.DataModel;
using Com.O2Bionics.ChatService.Settings;

namespace Com.O2Bionics.ChatService.Settings {

public partial class AgentSettings : SettingsBase {

public static readonly ReadOnlyDictionary<string, SettingsPropertyDescriptor> PropertyDescriptors =
new ReadOnlyDictionary<string, SettingsPropertyDescriptor>(
new Dictionary<string, SettingsPropertyDescriptor> {
{ "MediaCallProposalTimeout", new SettingsPropertyDescriptor<System.TimeSpan>(new TimeSpan(400000000)) },
{ "MediaCallConnectTimeout", new SettingsPropertyDescriptor<System.TimeSpan>(new TimeSpan(400000000)) },
});

public AgentSettings(ICollection<PROPERTY_BAG> records) : base(records, PropertyDescriptors) {}
public AgentSettings(WritableAgentSettings settings) : base(settings) {}

public System.TimeSpan MediaCallProposalTimeout {
get { return Get<System.TimeSpan>("MediaCallProposalTimeout"); }
}
public bool HasMediaCallProposalTimeout {
get { return Has("MediaCallProposalTimeout"); }
}
public System.TimeSpan MediaCallProposalTimeoutDefault {
get { return Default<System.TimeSpan>("MediaCallProposalTimeout"); }
}

public System.TimeSpan MediaCallConnectTimeout {
get { return Get<System.TimeSpan>("MediaCallConnectTimeout"); }
}
public bool HasMediaCallConnectTimeout {
get { return Has("MediaCallConnectTimeout"); }
}
public System.TimeSpan MediaCallConnectTimeoutDefault {
get { return Default<System.TimeSpan>("MediaCallConnectTimeout"); }
}
}

public partial class WritableAgentSettings : WritableSettingsBase {

public WritableAgentSettings(AgentSettings settings) : base(settings) {}
public WritableAgentSettings() : base(AgentSettings.PropertyDescriptors) {}

public System.TimeSpan MediaCallProposalTimeout {
get { return Get<System.TimeSpan>("MediaCallProposalTimeout"); }
set { Set("MediaCallProposalTimeout", value); }
}
public bool HasMediaCallProposalTimeout {
get { return Has("MediaCallProposalTimeout"); }
}
public System.TimeSpan MediaCallProposalTimeoutDefault {
get { return Default<System.TimeSpan>("MediaCallProposalTimeout"); }
}

public System.TimeSpan MediaCallConnectTimeout {
get { return Get<System.TimeSpan>("MediaCallConnectTimeout"); }
set { Set("MediaCallConnectTimeout", value); }
}
public bool HasMediaCallConnectTimeout {
get { return Has("MediaCallConnectTimeout"); }
}
public System.TimeSpan MediaCallConnectTimeoutDefault {
get { return Default<System.TimeSpan>("MediaCallConnectTimeout"); }
}
}
}
