//----------------------------------------------------------------------------------------------------
//    <auto-generated>
//    This code was generated by SettingsGenerator template.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//    </auto-generated>
//----------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Com.O2Bionics.ChatService.DataModel;
using Com.O2Bionics.ChatService.Settings;

namespace Com.O2Bionics.ChatService.Settings {

public partial class CustomerSettings : SettingsBase {

public static readonly ReadOnlyDictionary<string, SettingsPropertyDescriptor> PropertyDescriptors =
new ReadOnlyDictionary<string, SettingsPropertyDescriptor>(
new Dictionary<string, SettingsPropertyDescriptor> {
{ "MaxPagesInHistory", new SettingsPropertyDescriptor<int>(20) },
{ "IsVisitorCaptchaRequired", new SettingsPropertyDescriptor<bool>(false) },
{ "IsProactiveChatEnabled", new SettingsPropertyDescriptor<bool>(false) },
{ "Customization", new SettingsPropertyDescriptor<string>(null) },
});

public CustomerSettings(ICollection<PROPERTY_BAG> records) : base(records, PropertyDescriptors) {}
public CustomerSettings(WritableCustomerSettings settings) : base(settings) {}

public int MaxPagesInHistory {
get { return Get<int>("MaxPagesInHistory"); }
}
public bool HasMaxPagesInHistory {
get { return Has("MaxPagesInHistory"); }
}
public int MaxPagesInHistoryDefault {
get { return Default<int>("MaxPagesInHistory"); }
}

public bool IsVisitorCaptchaRequired {
get { return Get<bool>("IsVisitorCaptchaRequired"); }
}
public bool HasIsVisitorCaptchaRequired {
get { return Has("IsVisitorCaptchaRequired"); }
}
public bool IsVisitorCaptchaRequiredDefault {
get { return Default<bool>("IsVisitorCaptchaRequired"); }
}

public bool IsProactiveChatEnabled {
get { return Get<bool>("IsProactiveChatEnabled"); }
}
public bool HasIsProactiveChatEnabled {
get { return Has("IsProactiveChatEnabled"); }
}
public bool IsProactiveChatEnabledDefault {
get { return Default<bool>("IsProactiveChatEnabled"); }
}

public string Customization {
get { return Get<string>("Customization"); }
}
public bool HasCustomization {
get { return Has("Customization"); }
}
public string CustomizationDefault {
get { return Default<string>("Customization"); }
}
}

public partial class WritableCustomerSettings : WritableSettingsBase {

public WritableCustomerSettings(CustomerSettings settings) : base(settings) {}
public WritableCustomerSettings() : base(CustomerSettings.PropertyDescriptors) {}

public int MaxPagesInHistory {
get { return Get<int>("MaxPagesInHistory"); }
set { Set("MaxPagesInHistory", value); }
}
public bool HasMaxPagesInHistory {
get { return Has("MaxPagesInHistory"); }
}
public int MaxPagesInHistoryDefault {
get { return Default<int>("MaxPagesInHistory"); }
}

public bool IsVisitorCaptchaRequired {
get { return Get<bool>("IsVisitorCaptchaRequired"); }
set { Set("IsVisitorCaptchaRequired", value); }
}
public bool HasIsVisitorCaptchaRequired {
get { return Has("IsVisitorCaptchaRequired"); }
}
public bool IsVisitorCaptchaRequiredDefault {
get { return Default<bool>("IsVisitorCaptchaRequired"); }
}

public bool IsProactiveChatEnabled {
get { return Get<bool>("IsProactiveChatEnabled"); }
set { Set("IsProactiveChatEnabled", value); }
}
public bool HasIsProactiveChatEnabled {
get { return Has("IsProactiveChatEnabled"); }
}
public bool IsProactiveChatEnabledDefault {
get { return Default<bool>("IsProactiveChatEnabled"); }
}

public string Customization {
get { return Get<string>("Customization"); }
set { Set("Customization", value); }
}
public bool HasCustomization {
get { return Has("Customization"); }
}
public string CustomizationDefault {
get { return Default<string>("Customization"); }
}
}
}
