//----------------------------------------------------------------------------------------------------
//    <auto-generated>
//    This code was generated by SettingsGenerator template.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//    </auto-generated>
//----------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Com.O2Bionics.ChatService.DataModel;
using Com.O2Bionics.ChatService.Settings;

namespace Com.O2Bionics.ChatService.Settings {

public partial class ServiceSettings : SettingsBase {

public static readonly ReadOnlyDictionary<string, SettingsPropertyDescriptor> PropertyDescriptors =
new ReadOnlyDictionary<string, SettingsPropertyDescriptor>(
new Dictionary<string, SettingsPropertyDescriptor> {
{ "IntProperty", new SettingsPropertyDescriptor<int>(10) },
{ "IntNullableProperty", new SettingsPropertyDescriptor<System.Nullable<int>>(null) },
{ "StringProperty", new SettingsPropertyDescriptor<string>("a") },
{ "AgentEventSubscriptions", new SettingsPropertyDescriptor<string>("[]") },
{ "VisitorEventSubscriptions", new SettingsPropertyDescriptor<string>("[]") },
{ "PasswordResetCodeTimeout", new SettingsPropertyDescriptor<System.TimeSpan>(new TimeSpan(864000000000)) },
{ "AgentSessionDisconnectTimeout", new SettingsPropertyDescriptor<System.TimeSpan>(new TimeSpan(350000000)) },
{ "MediaCallDisconnectStopTimeout", new SettingsPropertyDescriptor<System.TimeSpan>(new TimeSpan(300000000)) },
});

public ServiceSettings(ICollection<PROPERTY_BAG> records) : base(records, PropertyDescriptors) {}
public ServiceSettings(WritableServiceSettings settings) : base(settings) {}

public int IntProperty {
get { return Get<int>("IntProperty"); }
}
public bool HasIntProperty {
get { return Has("IntProperty"); }
}
public int IntPropertyDefault {
get { return Default<int>("IntProperty"); }
}

public System.Nullable<int> IntNullableProperty {
get { return Get<System.Nullable<int>>("IntNullableProperty"); }
}
public bool HasIntNullableProperty {
get { return Has("IntNullableProperty"); }
}
public System.Nullable<int> IntNullablePropertyDefault {
get { return Default<System.Nullable<int>>("IntNullableProperty"); }
}

public string StringProperty {
get { return Get<string>("StringProperty"); }
}
public bool HasStringProperty {
get { return Has("StringProperty"); }
}
public string StringPropertyDefault {
get { return Default<string>("StringProperty"); }
}

public string AgentEventSubscriptions {
get { return Get<string>("AgentEventSubscriptions"); }
}
public bool HasAgentEventSubscriptions {
get { return Has("AgentEventSubscriptions"); }
}
public string AgentEventSubscriptionsDefault {
get { return Default<string>("AgentEventSubscriptions"); }
}

public string VisitorEventSubscriptions {
get { return Get<string>("VisitorEventSubscriptions"); }
}
public bool HasVisitorEventSubscriptions {
get { return Has("VisitorEventSubscriptions"); }
}
public string VisitorEventSubscriptionsDefault {
get { return Default<string>("VisitorEventSubscriptions"); }
}

public System.TimeSpan PasswordResetCodeTimeout {
get { return Get<System.TimeSpan>("PasswordResetCodeTimeout"); }
}
public bool HasPasswordResetCodeTimeout {
get { return Has("PasswordResetCodeTimeout"); }
}
public System.TimeSpan PasswordResetCodeTimeoutDefault {
get { return Default<System.TimeSpan>("PasswordResetCodeTimeout"); }
}

public System.TimeSpan AgentSessionDisconnectTimeout {
get { return Get<System.TimeSpan>("AgentSessionDisconnectTimeout"); }
}
public bool HasAgentSessionDisconnectTimeout {
get { return Has("AgentSessionDisconnectTimeout"); }
}
public System.TimeSpan AgentSessionDisconnectTimeoutDefault {
get { return Default<System.TimeSpan>("AgentSessionDisconnectTimeout"); }
}

public System.TimeSpan MediaCallDisconnectStopTimeout {
get { return Get<System.TimeSpan>("MediaCallDisconnectStopTimeout"); }
}
public bool HasMediaCallDisconnectStopTimeout {
get { return Has("MediaCallDisconnectStopTimeout"); }
}
public System.TimeSpan MediaCallDisconnectStopTimeoutDefault {
get { return Default<System.TimeSpan>("MediaCallDisconnectStopTimeout"); }
}
}

public partial class WritableServiceSettings : WritableSettingsBase {

public WritableServiceSettings(ServiceSettings settings) : base(settings) {}
public WritableServiceSettings() : base(ServiceSettings.PropertyDescriptors) {}

public int IntProperty {
get { return Get<int>("IntProperty"); }
set { Set("IntProperty", value); }
}
public bool HasIntProperty {
get { return Has("IntProperty"); }
}
public int IntPropertyDefault {
get { return Default<int>("IntProperty"); }
}

public System.Nullable<int> IntNullableProperty {
get { return Get<System.Nullable<int>>("IntNullableProperty"); }
set { Set("IntNullableProperty", value); }
}
public bool HasIntNullableProperty {
get { return Has("IntNullableProperty"); }
}
public System.Nullable<int> IntNullablePropertyDefault {
get { return Default<System.Nullable<int>>("IntNullableProperty"); }
}

public string StringProperty {
get { return Get<string>("StringProperty"); }
set { Set("StringProperty", value); }
}
public bool HasStringProperty {
get { return Has("StringProperty"); }
}
public string StringPropertyDefault {
get { return Default<string>("StringProperty"); }
}

public string AgentEventSubscriptions {
get { return Get<string>("AgentEventSubscriptions"); }
set { Set("AgentEventSubscriptions", value); }
}
public bool HasAgentEventSubscriptions {
get { return Has("AgentEventSubscriptions"); }
}
public string AgentEventSubscriptionsDefault {
get { return Default<string>("AgentEventSubscriptions"); }
}

public string VisitorEventSubscriptions {
get { return Get<string>("VisitorEventSubscriptions"); }
set { Set("VisitorEventSubscriptions", value); }
}
public bool HasVisitorEventSubscriptions {
get { return Has("VisitorEventSubscriptions"); }
}
public string VisitorEventSubscriptionsDefault {
get { return Default<string>("VisitorEventSubscriptions"); }
}

public System.TimeSpan PasswordResetCodeTimeout {
get { return Get<System.TimeSpan>("PasswordResetCodeTimeout"); }
set { Set("PasswordResetCodeTimeout", value); }
}
public bool HasPasswordResetCodeTimeout {
get { return Has("PasswordResetCodeTimeout"); }
}
public System.TimeSpan PasswordResetCodeTimeoutDefault {
get { return Default<System.TimeSpan>("PasswordResetCodeTimeout"); }
}

public System.TimeSpan AgentSessionDisconnectTimeout {
get { return Get<System.TimeSpan>("AgentSessionDisconnectTimeout"); }
set { Set("AgentSessionDisconnectTimeout", value); }
}
public bool HasAgentSessionDisconnectTimeout {
get { return Has("AgentSessionDisconnectTimeout"); }
}
public System.TimeSpan AgentSessionDisconnectTimeoutDefault {
get { return Default<System.TimeSpan>("AgentSessionDisconnectTimeout"); }
}

public System.TimeSpan MediaCallDisconnectStopTimeout {
get { return Get<System.TimeSpan>("MediaCallDisconnectStopTimeout"); }
set { Set("MediaCallDisconnectStopTimeout", value); }
}
public bool HasMediaCallDisconnectStopTimeout {
get { return Has("MediaCallDisconnectStopTimeout"); }
}
public System.TimeSpan MediaCallDisconnectStopTimeoutDefault {
get { return Default<System.TimeSpan>("MediaCallDisconnectStopTimeout"); }
}
}
}
