//----------------------------------------------------------------------------------------------------
//    <auto-generated>
//    This code was generated by SettingsGenerator template.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//    </auto-generated>
//----------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Com.O2Bionics.ChatService.DataModel;
using Com.O2Bionics.ChatService.Settings;

namespace Com.O2Bionics.ChatService.Tests.SettingsTests {

public partial class TestSettings : SettingsBase {

public static readonly ReadOnlyDictionary<string, SettingsPropertyDescriptor> PropertyDescriptors =
new ReadOnlyDictionary<string, SettingsPropertyDescriptor>(
new Dictionary<string, SettingsPropertyDescriptor> {
{ "BoolProperty", new SettingsPropertyDescriptor<bool>(true) },
{ "NullableBoolProperty1", new SettingsPropertyDescriptor<System.Nullable<bool>>(true) },
{ "NullableBoolProperty2", new SettingsPropertyDescriptor<System.Nullable<bool>>(null) },
{ "IntProperty", new SettingsPropertyDescriptor<int>(20) },
{ "NullableIntProperty1", new SettingsPropertyDescriptor<System.Nullable<int>>(20) },
{ "NullableIntProperty2", new SettingsPropertyDescriptor<System.Nullable<int>>(null) },
{ "FloatProperty", new SettingsPropertyDescriptor<float>(20) },
{ "NullableFloatProperty1", new SettingsPropertyDescriptor<System.Nullable<float>>(20) },
{ "NullableFloatProperty2", new SettingsPropertyDescriptor<System.Nullable<float>>(null) },
{ "DoubleProperty", new SettingsPropertyDescriptor<double>(20) },
{ "NullableDoubleProperty1", new SettingsPropertyDescriptor<System.Nullable<double>>(20) },
{ "NullableDoubleProperty2", new SettingsPropertyDescriptor<System.Nullable<double>>(null) },
{ "DecimalProperty", new SettingsPropertyDescriptor<decimal>(20) },
{ "NullableDecimalProperty1", new SettingsPropertyDescriptor<System.Nullable<decimal>>(20) },
{ "NullableDecimalProperty2", new SettingsPropertyDescriptor<System.Nullable<decimal>>(null) },
{ "StringProperty1", new SettingsPropertyDescriptor<string>("te\"stTEST1") },
{ "StringProperty2", new SettingsPropertyDescriptor<string>(null) },
{ "DateTimeProperty", new SettingsPropertyDescriptor<System.DateTime>(new DateTime(2014,1,2,3,4,5)) },
{ "NullableDateTimeProperty1", new SettingsPropertyDescriptor<System.Nullable<System.DateTime>>(new DateTime(2014,1,2,3,4,5)) },
{ "NullableDateTimeProperty2", new SettingsPropertyDescriptor<System.Nullable<System.DateTime>>(null) },
{ "TimeSpanProperty", new SettingsPropertyDescriptor<System.TimeSpan>(new TimeSpan(72000000000)) },
{ "NullableTimeSpanProperty1", new SettingsPropertyDescriptor<System.Nullable<System.TimeSpan>>(new TimeSpan(432000000000)) },
{ "NullableTimeSpanProperty2", new SettingsPropertyDescriptor<System.Nullable<System.TimeSpan>>(null) },
});

public TestSettings(ICollection<PROPERTY_BAG> records) : base(records, PropertyDescriptors) {}
public TestSettings(WritableTestSettings settings) : base(settings) {}

public bool BoolProperty {
get { return Get<bool>("BoolProperty"); }
}
public bool HasBoolProperty {
get { return Has("BoolProperty"); }
}
public bool BoolPropertyDefault {
get { return Default<bool>("BoolProperty"); }
}

public System.Nullable<bool> NullableBoolProperty1 {
get { return Get<System.Nullable<bool>>("NullableBoolProperty1"); }
}
public bool HasNullableBoolProperty1 {
get { return Has("NullableBoolProperty1"); }
}
public System.Nullable<bool> NullableBoolProperty1Default {
get { return Default<System.Nullable<bool>>("NullableBoolProperty1"); }
}

public System.Nullable<bool> NullableBoolProperty2 {
get { return Get<System.Nullable<bool>>("NullableBoolProperty2"); }
}
public bool HasNullableBoolProperty2 {
get { return Has("NullableBoolProperty2"); }
}
public System.Nullable<bool> NullableBoolProperty2Default {
get { return Default<System.Nullable<bool>>("NullableBoolProperty2"); }
}

public int IntProperty {
get { return Get<int>("IntProperty"); }
}
public bool HasIntProperty {
get { return Has("IntProperty"); }
}
public int IntPropertyDefault {
get { return Default<int>("IntProperty"); }
}

public System.Nullable<int> NullableIntProperty1 {
get { return Get<System.Nullable<int>>("NullableIntProperty1"); }
}
public bool HasNullableIntProperty1 {
get { return Has("NullableIntProperty1"); }
}
public System.Nullable<int> NullableIntProperty1Default {
get { return Default<System.Nullable<int>>("NullableIntProperty1"); }
}

public System.Nullable<int> NullableIntProperty2 {
get { return Get<System.Nullable<int>>("NullableIntProperty2"); }
}
public bool HasNullableIntProperty2 {
get { return Has("NullableIntProperty2"); }
}
public System.Nullable<int> NullableIntProperty2Default {
get { return Default<System.Nullable<int>>("NullableIntProperty2"); }
}

public float FloatProperty {
get { return Get<float>("FloatProperty"); }
}
public bool HasFloatProperty {
get { return Has("FloatProperty"); }
}
public float FloatPropertyDefault {
get { return Default<float>("FloatProperty"); }
}

public System.Nullable<float> NullableFloatProperty1 {
get { return Get<System.Nullable<float>>("NullableFloatProperty1"); }
}
public bool HasNullableFloatProperty1 {
get { return Has("NullableFloatProperty1"); }
}
public System.Nullable<float> NullableFloatProperty1Default {
get { return Default<System.Nullable<float>>("NullableFloatProperty1"); }
}

public System.Nullable<float> NullableFloatProperty2 {
get { return Get<System.Nullable<float>>("NullableFloatProperty2"); }
}
public bool HasNullableFloatProperty2 {
get { return Has("NullableFloatProperty2"); }
}
public System.Nullable<float> NullableFloatProperty2Default {
get { return Default<System.Nullable<float>>("NullableFloatProperty2"); }
}

public double DoubleProperty {
get { return Get<double>("DoubleProperty"); }
}
public bool HasDoubleProperty {
get { return Has("DoubleProperty"); }
}
public double DoublePropertyDefault {
get { return Default<double>("DoubleProperty"); }
}

public System.Nullable<double> NullableDoubleProperty1 {
get { return Get<System.Nullable<double>>("NullableDoubleProperty1"); }
}
public bool HasNullableDoubleProperty1 {
get { return Has("NullableDoubleProperty1"); }
}
public System.Nullable<double> NullableDoubleProperty1Default {
get { return Default<System.Nullable<double>>("NullableDoubleProperty1"); }
}

public System.Nullable<double> NullableDoubleProperty2 {
get { return Get<System.Nullable<double>>("NullableDoubleProperty2"); }
}
public bool HasNullableDoubleProperty2 {
get { return Has("NullableDoubleProperty2"); }
}
public System.Nullable<double> NullableDoubleProperty2Default {
get { return Default<System.Nullable<double>>("NullableDoubleProperty2"); }
}

public decimal DecimalProperty {
get { return Get<decimal>("DecimalProperty"); }
}
public bool HasDecimalProperty {
get { return Has("DecimalProperty"); }
}
public decimal DecimalPropertyDefault {
get { return Default<decimal>("DecimalProperty"); }
}

public System.Nullable<decimal> NullableDecimalProperty1 {
get { return Get<System.Nullable<decimal>>("NullableDecimalProperty1"); }
}
public bool HasNullableDecimalProperty1 {
get { return Has("NullableDecimalProperty1"); }
}
public System.Nullable<decimal> NullableDecimalProperty1Default {
get { return Default<System.Nullable<decimal>>("NullableDecimalProperty1"); }
}

public System.Nullable<decimal> NullableDecimalProperty2 {
get { return Get<System.Nullable<decimal>>("NullableDecimalProperty2"); }
}
public bool HasNullableDecimalProperty2 {
get { return Has("NullableDecimalProperty2"); }
}
public System.Nullable<decimal> NullableDecimalProperty2Default {
get { return Default<System.Nullable<decimal>>("NullableDecimalProperty2"); }
}

public string StringProperty1 {
get { return Get<string>("StringProperty1"); }
}
public bool HasStringProperty1 {
get { return Has("StringProperty1"); }
}
public string StringProperty1Default {
get { return Default<string>("StringProperty1"); }
}

public string StringProperty2 {
get { return Get<string>("StringProperty2"); }
}
public bool HasStringProperty2 {
get { return Has("StringProperty2"); }
}
public string StringProperty2Default {
get { return Default<string>("StringProperty2"); }
}

public System.DateTime DateTimeProperty {
get { return Get<System.DateTime>("DateTimeProperty"); }
}
public bool HasDateTimeProperty {
get { return Has("DateTimeProperty"); }
}
public System.DateTime DateTimePropertyDefault {
get { return Default<System.DateTime>("DateTimeProperty"); }
}

public System.Nullable<System.DateTime> NullableDateTimeProperty1 {
get { return Get<System.Nullable<System.DateTime>>("NullableDateTimeProperty1"); }
}
public bool HasNullableDateTimeProperty1 {
get { return Has("NullableDateTimeProperty1"); }
}
public System.Nullable<System.DateTime> NullableDateTimeProperty1Default {
get { return Default<System.Nullable<System.DateTime>>("NullableDateTimeProperty1"); }
}

public System.Nullable<System.DateTime> NullableDateTimeProperty2 {
get { return Get<System.Nullable<System.DateTime>>("NullableDateTimeProperty2"); }
}
public bool HasNullableDateTimeProperty2 {
get { return Has("NullableDateTimeProperty2"); }
}
public System.Nullable<System.DateTime> NullableDateTimeProperty2Default {
get { return Default<System.Nullable<System.DateTime>>("NullableDateTimeProperty2"); }
}

public System.TimeSpan TimeSpanProperty {
get { return Get<System.TimeSpan>("TimeSpanProperty"); }
}
public bool HasTimeSpanProperty {
get { return Has("TimeSpanProperty"); }
}
public System.TimeSpan TimeSpanPropertyDefault {
get { return Default<System.TimeSpan>("TimeSpanProperty"); }
}

public System.Nullable<System.TimeSpan> NullableTimeSpanProperty1 {
get { return Get<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty1"); }
}
public bool HasNullableTimeSpanProperty1 {
get { return Has("NullableTimeSpanProperty1"); }
}
public System.Nullable<System.TimeSpan> NullableTimeSpanProperty1Default {
get { return Default<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty1"); }
}

public System.Nullable<System.TimeSpan> NullableTimeSpanProperty2 {
get { return Get<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty2"); }
}
public bool HasNullableTimeSpanProperty2 {
get { return Has("NullableTimeSpanProperty2"); }
}
public System.Nullable<System.TimeSpan> NullableTimeSpanProperty2Default {
get { return Default<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty2"); }
}
}

public partial class WritableTestSettings : WritableSettingsBase {

public WritableTestSettings(TestSettings settings) : base(settings) {}
public WritableTestSettings() : base(TestSettings.PropertyDescriptors) {}

public bool BoolProperty {
get { return Get<bool>("BoolProperty"); }
set { Set("BoolProperty", value); }
}
public bool HasBoolProperty {
get { return Has("BoolProperty"); }
}
public bool BoolPropertyDefault {
get { return Default<bool>("BoolProperty"); }
}

public System.Nullable<bool> NullableBoolProperty1 {
get { return Get<System.Nullable<bool>>("NullableBoolProperty1"); }
set { Set("NullableBoolProperty1", value); }
}
public bool HasNullableBoolProperty1 {
get { return Has("NullableBoolProperty1"); }
}
public System.Nullable<bool> NullableBoolProperty1Default {
get { return Default<System.Nullable<bool>>("NullableBoolProperty1"); }
}

public System.Nullable<bool> NullableBoolProperty2 {
get { return Get<System.Nullable<bool>>("NullableBoolProperty2"); }
set { Set("NullableBoolProperty2", value); }
}
public bool HasNullableBoolProperty2 {
get { return Has("NullableBoolProperty2"); }
}
public System.Nullable<bool> NullableBoolProperty2Default {
get { return Default<System.Nullable<bool>>("NullableBoolProperty2"); }
}

public int IntProperty {
get { return Get<int>("IntProperty"); }
set { Set("IntProperty", value); }
}
public bool HasIntProperty {
get { return Has("IntProperty"); }
}
public int IntPropertyDefault {
get { return Default<int>("IntProperty"); }
}

public System.Nullable<int> NullableIntProperty1 {
get { return Get<System.Nullable<int>>("NullableIntProperty1"); }
set { Set("NullableIntProperty1", value); }
}
public bool HasNullableIntProperty1 {
get { return Has("NullableIntProperty1"); }
}
public System.Nullable<int> NullableIntProperty1Default {
get { return Default<System.Nullable<int>>("NullableIntProperty1"); }
}

public System.Nullable<int> NullableIntProperty2 {
get { return Get<System.Nullable<int>>("NullableIntProperty2"); }
set { Set("NullableIntProperty2", value); }
}
public bool HasNullableIntProperty2 {
get { return Has("NullableIntProperty2"); }
}
public System.Nullable<int> NullableIntProperty2Default {
get { return Default<System.Nullable<int>>("NullableIntProperty2"); }
}

public float FloatProperty {
get { return Get<float>("FloatProperty"); }
set { Set("FloatProperty", value); }
}
public bool HasFloatProperty {
get { return Has("FloatProperty"); }
}
public float FloatPropertyDefault {
get { return Default<float>("FloatProperty"); }
}

public System.Nullable<float> NullableFloatProperty1 {
get { return Get<System.Nullable<float>>("NullableFloatProperty1"); }
set { Set("NullableFloatProperty1", value); }
}
public bool HasNullableFloatProperty1 {
get { return Has("NullableFloatProperty1"); }
}
public System.Nullable<float> NullableFloatProperty1Default {
get { return Default<System.Nullable<float>>("NullableFloatProperty1"); }
}

public System.Nullable<float> NullableFloatProperty2 {
get { return Get<System.Nullable<float>>("NullableFloatProperty2"); }
set { Set("NullableFloatProperty2", value); }
}
public bool HasNullableFloatProperty2 {
get { return Has("NullableFloatProperty2"); }
}
public System.Nullable<float> NullableFloatProperty2Default {
get { return Default<System.Nullable<float>>("NullableFloatProperty2"); }
}

public double DoubleProperty {
get { return Get<double>("DoubleProperty"); }
set { Set("DoubleProperty", value); }
}
public bool HasDoubleProperty {
get { return Has("DoubleProperty"); }
}
public double DoublePropertyDefault {
get { return Default<double>("DoubleProperty"); }
}

public System.Nullable<double> NullableDoubleProperty1 {
get { return Get<System.Nullable<double>>("NullableDoubleProperty1"); }
set { Set("NullableDoubleProperty1", value); }
}
public bool HasNullableDoubleProperty1 {
get { return Has("NullableDoubleProperty1"); }
}
public System.Nullable<double> NullableDoubleProperty1Default {
get { return Default<System.Nullable<double>>("NullableDoubleProperty1"); }
}

public System.Nullable<double> NullableDoubleProperty2 {
get { return Get<System.Nullable<double>>("NullableDoubleProperty2"); }
set { Set("NullableDoubleProperty2", value); }
}
public bool HasNullableDoubleProperty2 {
get { return Has("NullableDoubleProperty2"); }
}
public System.Nullable<double> NullableDoubleProperty2Default {
get { return Default<System.Nullable<double>>("NullableDoubleProperty2"); }
}

public decimal DecimalProperty {
get { return Get<decimal>("DecimalProperty"); }
set { Set("DecimalProperty", value); }
}
public bool HasDecimalProperty {
get { return Has("DecimalProperty"); }
}
public decimal DecimalPropertyDefault {
get { return Default<decimal>("DecimalProperty"); }
}

public System.Nullable<decimal> NullableDecimalProperty1 {
get { return Get<System.Nullable<decimal>>("NullableDecimalProperty1"); }
set { Set("NullableDecimalProperty1", value); }
}
public bool HasNullableDecimalProperty1 {
get { return Has("NullableDecimalProperty1"); }
}
public System.Nullable<decimal> NullableDecimalProperty1Default {
get { return Default<System.Nullable<decimal>>("NullableDecimalProperty1"); }
}

public System.Nullable<decimal> NullableDecimalProperty2 {
get { return Get<System.Nullable<decimal>>("NullableDecimalProperty2"); }
set { Set("NullableDecimalProperty2", value); }
}
public bool HasNullableDecimalProperty2 {
get { return Has("NullableDecimalProperty2"); }
}
public System.Nullable<decimal> NullableDecimalProperty2Default {
get { return Default<System.Nullable<decimal>>("NullableDecimalProperty2"); }
}

public string StringProperty1 {
get { return Get<string>("StringProperty1"); }
set { Set("StringProperty1", value); }
}
public bool HasStringProperty1 {
get { return Has("StringProperty1"); }
}
public string StringProperty1Default {
get { return Default<string>("StringProperty1"); }
}

public string StringProperty2 {
get { return Get<string>("StringProperty2"); }
set { Set("StringProperty2", value); }
}
public bool HasStringProperty2 {
get { return Has("StringProperty2"); }
}
public string StringProperty2Default {
get { return Default<string>("StringProperty2"); }
}

public System.DateTime DateTimeProperty {
get { return Get<System.DateTime>("DateTimeProperty"); }
set { Set("DateTimeProperty", value); }
}
public bool HasDateTimeProperty {
get { return Has("DateTimeProperty"); }
}
public System.DateTime DateTimePropertyDefault {
get { return Default<System.DateTime>("DateTimeProperty"); }
}

public System.Nullable<System.DateTime> NullableDateTimeProperty1 {
get { return Get<System.Nullable<System.DateTime>>("NullableDateTimeProperty1"); }
set { Set("NullableDateTimeProperty1", value); }
}
public bool HasNullableDateTimeProperty1 {
get { return Has("NullableDateTimeProperty1"); }
}
public System.Nullable<System.DateTime> NullableDateTimeProperty1Default {
get { return Default<System.Nullable<System.DateTime>>("NullableDateTimeProperty1"); }
}

public System.Nullable<System.DateTime> NullableDateTimeProperty2 {
get { return Get<System.Nullable<System.DateTime>>("NullableDateTimeProperty2"); }
set { Set("NullableDateTimeProperty2", value); }
}
public bool HasNullableDateTimeProperty2 {
get { return Has("NullableDateTimeProperty2"); }
}
public System.Nullable<System.DateTime> NullableDateTimeProperty2Default {
get { return Default<System.Nullable<System.DateTime>>("NullableDateTimeProperty2"); }
}

public System.TimeSpan TimeSpanProperty {
get { return Get<System.TimeSpan>("TimeSpanProperty"); }
set { Set("TimeSpanProperty", value); }
}
public bool HasTimeSpanProperty {
get { return Has("TimeSpanProperty"); }
}
public System.TimeSpan TimeSpanPropertyDefault {
get { return Default<System.TimeSpan>("TimeSpanProperty"); }
}

public System.Nullable<System.TimeSpan> NullableTimeSpanProperty1 {
get { return Get<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty1"); }
set { Set("NullableTimeSpanProperty1", value); }
}
public bool HasNullableTimeSpanProperty1 {
get { return Has("NullableTimeSpanProperty1"); }
}
public System.Nullable<System.TimeSpan> NullableTimeSpanProperty1Default {
get { return Default<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty1"); }
}

public System.Nullable<System.TimeSpan> NullableTimeSpanProperty2 {
get { return Get<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty2"); }
set { Set("NullableTimeSpanProperty2", value); }
}
public bool HasNullableTimeSpanProperty2 {
get { return Has("NullableTimeSpanProperty2"); }
}
public System.Nullable<System.TimeSpan> NullableTimeSpanProperty2Default {
get { return Default<System.Nullable<System.TimeSpan>>("NullableTimeSpanProperty2"); }
}
}
}
