//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.O2Bionics.ChatService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.O2Bionics.ChatService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add an audit event {0}, customer={1}, unknownDomain=&apos;{2}&apos;..
        /// </summary>
        internal static string AddAuditEventFailedError1 {
            get {
                return ResourceManager.GetString("AddAuditEventFailedError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- CHAT SERVICE SPECIFIC
        ///
        ///-- DICTIONARIES
        ///
        ///CREATE TABLE OBJECT_STATUS
        ///(
        ///	OBJECT_STATUS_ID			NUMBER(1) NOT NULL ,
        ///	NAME						VARCHAR2(32) NOT NULL ,
        ///	DESCRIPTION					VARCHAR2(256) NULL 
        ///);
        ///ALTER TABLE OBJECT_STATUS ADD CONSTRAINT PK_OBJECT_STATUS PRIMARY KEY (OBJECT_STATUS_ID);
        ///INSERT INTO OBJECT_STATUS VALUES (0, &apos;ACTIVE&apos;, &apos;Object is active&apos;);
        ///INSERT INTO OBJECT_STATUS VALUES (1, &apos;DISABLED&apos;, &apos;Object is disabled&apos;);
        ///INSERT INTO OBJECT_STATUS VALUES (2, &apos;DELETED&apos;, &apos;Object is deleted&apos;);
        ///
        ///CREATE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the data for {0}..
        /// </summary>
        internal static string LoadFailedForDateError1 {
            get {
                return ResourceManager.GetString("LoadFailedForDateError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE ADD_UPDATE_WIDGET_LOADS
        ///(
        ///  pCUSTOMER_ID IN WIDGET_LOAD.CUSTOMER_ID%TYPE
        ///, pUPDATED IN WIDGET_LOAD.UPDATED%TYPE
        ///, pINCREMENT IN WIDGET_LOAD.LOADS%TYPE
        ///, pISOVERLOAD IN WIDGET_LOAD.ISOVERLOAD%TYPE DEFAULT NULL
        ///, pLOADS OUT WIDGET_LOAD.LOADS%TYPE
        ///, pISSET OUT WIDGET_LOAD.ISOVERLOAD%TYPE -- Whether the value has changed from 0 to 1.
        ///)
        ///AS 
        ///  max_attempts NUMBER := 10;
        ///  attempts NUMBER := 0;
        ///  stamp WIDGET_LOAD.STAMP%TYPE := NULL;
        ///  isOverRead WIDGET_LOAD.ISOVERLOAD%TYPE := NULL;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string procedures {
            get {
                return ResourceManager.GetString("procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found, skey={0}..
        /// </summary>
        internal static string UserNotFoundError1 {
            get {
                return ResourceManager.GetString("UserNotFoundError1", resourceCulture);
            }
        }
    }
}
