version: '3.4'

services:
    
  # MSSQL
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 
  
  # O2 Account  
  identity-api:
    image: ${REGISTRY:-o2bionics}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata
   
  # O2 Certificate
  certificate-api:
    image: ${REGISTRY:-o2bionics}/o2-certificate.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Certificate/O2.Certificate.API/Dockerfile
    depends_on:
      - sqldata