//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.O2Bionics.PageTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.O2Bionics.PageTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE `add_record`(
        ///	in timestampUtc datetime,
        ///    in ipAddressId int unsigned,
        ///    in ip varbinary(16),
        ///    in ipCountryName varchar(128) character set utf8,
        ///    in ipCityName varchar(128) character set utf8,
        ///    in ipLatitude int,
        ///    in ipLongitude int,
        ///    in customerId int unsigned,
        ///    in visitorId int unsigned,
        ///    in visitorExternalId varchar(256) character set utf8,
        ///    in timezoneOffset int,
        ///    in timezoneDescription varchar(128) character set utf8,
        ///    in userAgentText va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string add_record {
            get {
                return ResourceManager.GetString("add_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} must have Visitor ({1})..
        /// </summary>
        internal static string CustomerMustHaveVisitorError2 {
            get {
                return ResourceManager.GetString("CustomerMustHaveVisitorError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET FOREIGN_KEY_CHECKS=0; 
        ///
        ///DROP TABLE IF EXISTS `ip_country`;
        ///CREATE TABLE `ip_country` (
        ///  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
        ///  `name` varchar(128) NOT NULL,
        ///  PRIMARY KEY (`id`),
        ///  UNIQUE KEY `ip_country_name_UNIQUE` (`name`)
        ///) ENGINE=InnoDB DEFAULT CHARSET=utf8;
        ///
        ///DROP TABLE IF EXISTS `ip_city`;
        ///CREATE TABLE `ip_city` (
        ///  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
        ///  `name` varchar(128) NOT NULL,
        ///  PRIMARY KEY (`id`),
        ///  UNIQUE KEY `ip_city_name_UNIQUE` (`name`)
        ///) ENGINE=Inn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
    }
}
