//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.O2Bionics.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.O2Bionics.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted existing kibana object &apos;{0}/{1}&apos;, elapsed {2} ms..
        /// </summary>
        internal static string DeletedExistingKibanaObject3 {
            get {
                return ResourceManager.GetString("DeletedExistingKibanaObject3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} existing objects from Elastic Kibana at &apos;{1}&apos;, index = &apos;{2}&apos;, elapsed {3} ms..
        /// </summary>
        internal static string DeleteExistingKibanaObjectsReport4 {
            get {
                return ResourceManager.GetString("DeleteExistingKibanaObjectsReport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting existing Elastic Kibana object: &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorDeletingExistingKibanaObject1 {
            get {
                return ResourceManager.GetString("ErrorDeletingExistingKibanaObject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting an existing object: &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorDeletingExistingObject1 {
            get {
                return ResourceManager.GetString("ErrorDeletingExistingObject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Dashboard import to Elastic Kibana at &apos;{1}&apos; took {2} ms, response= &apos;
        ///
        ///{3}
        ///
        ///&apos;.
        /// </summary>
        internal static string ImportToKibanaReport4 {
            get {
                return ResourceManager.GetString("ImportToKibanaReport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index has been created in {0} ms..
        /// </summary>
        internal static string IndexCreateadInMs1 {
            get {
                return ResourceManager.GetString("IndexCreateadInMs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index has been deleted in {0} ms..
        /// </summary>
        internal static string IndexDeletedInMs1 {
            get {
                return ResourceManager.GetString("IndexDeletedInMs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to re-create the Audit Trail Kibana &apos;{0}&apos; at &apos;{1}&apos;, using the Elastic Search index &apos;{2}&apos; at &apos;{3}&apos;, run:
        ///{4} {5}
        ///
        ///In order to re-create the Error Tracker Kibana &apos;{6}&apos; at &apos;{1}&apos;, using the Elastic Search index &apos;{7}&apos; at &apos;{8}&apos;, run:
        ///{4} {9}.
        /// </summary>
        internal static string KibanaCommandUsage10 {
            get {
                return ResourceManager.GetString("KibanaCommandUsage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program elapsed {0} ms..
        /// </summary>
        internal static string ProgramElapsedMs1 {
            get {
                return ResourceManager.GetString("ProgramElapsedMs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Elastic Kibana at &apos;{1}&apos; default index pattern set took {2} ms, response= &apos;
        ///
        ///{3}
        ///
        ///&apos;.
        /// </summary>
        internal static string SetDefaultIndexPatternReport4 {
            get {
                return ResourceManager.GetString("SetDefaultIndexPatternReport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start creating the index &apos;{0}&apos; at &apos;{1}&apos;..
        /// </summary>
        internal static string StartCreatingIndex2 {
            get {
                return ResourceManager.GetString("StartCreatingIndex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start deleting the index &apos;{0}&apos; at &apos;{1}&apos;..
        /// </summary>
        internal static string StartDeletingIndex2 {
            get {
                return ResourceManager.GetString("StartDeletingIndex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start importing {0} to Elastic Kibana at &apos;{1}&apos;..
        /// </summary>
        internal static string StartKibanaImport2 {
            get {
                return ResourceManager.GetString("StartKibanaImport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to create the Elastic index &apos;{0}&apos; at &apos;{1}&apos;, run:
        ///{2} {3}
        ///
        ///To delete and then create the Elastic index &apos;{0}&apos; at &apos;{1}&apos;, run:
        ///{2} {4}.
        /// </summary>
        internal static string Usage5 {
            get {
                return ResourceManager.GetString("Usage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the file &apos;{0}&apos;.
        ///.
        /// </summary>
        internal static string UsingConfigFile1 {
            get {
                return ResourceManager.GetString("UsingConfigFile1", resourceCulture);
            }
        }
    }
}
